title: "Rodrigo Alejandre"
tagline: "Technical Artist Game Developer"
description: >-
I’m a Game Designer & QA professional 
who bridges creative intuition with 
data-driven quality strategy.
email: "roderykz@gmail.com"
cta_label: "Start a project"

url: "https://duaelist.github.io/"
baseurl: ""

social:
  linkedin: "https://www.linkedin.com/in/duael/"
  artstation: "https://www.artstation.com/roderykzal"
  instagram: "https://www.instagram.com/duaelist/"

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
